spring.application.name=lvtu-server
server.port=8080

# æ°æ®åºéç½®
spring.datasource.url=jdbc:mysql://localhost:3306/lvtu_db
spring.datasource.username=yc
spring.datasource.password=Yc20050609!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis éç½®
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# åé¡µéç½®
pagehelper.helperDialect=mysql
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql
